### ISSUE TITLE
NameError: name 'np' is not defined

### ISSUE THREAD

**Issue by yashrsharma44** [nishnik/KSNS#1]
When I ran `python recommend.py`, it printed some subject codes, and then it showed some error traceback :
```
Traceback (most recent call last):
  File "recommend.py", line 46, in <module>
    matrix = np.zeros((len(data), len(corpora)))
NameError: name 'np' is not defined
```
I am quite new with this, so I might not have posted a correct issue. Looking back in the code, I did find `np` is not defined. So one can have a look to this.

**Comment by djbarnwal** [comment]
@yashrsharma44 Add `import numpy as np` along with the other imports.

**Comment by nishnik** [comment]
I changed that in the code too, now it will run out-of-the-box.
